{"name": "test_sub[int_case_fail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 99 == 200\n +  where 99 = round(99, 2)", "trace": "self = <hogwarts_learn.Test_pytestcase1.test_zuoye2.TestCalculator object at 0x0000022925005A00>\nget_calc = <Cal_method.funcal.Calculator object at 0x0000022924F71370>, a = 100, b = 1, expect = 200\n\n    @pytest.mark.run(order=2)\n    @pytest.mark.parametrize('a,b,expect', get_datas()['SUB']['parametrize'], ids=get_datas()['SUB']['ids'])\n    def test_sub(self,get_calc, a, b, expect):\n        result = get_calc.sub(a, b)\n>       assert round(result, 2) == expect\nE       assert 99 == 200\nE        +  where 99 = round(99, 2)\n\ntest_zuoye2.py:21: AssertionError"}, "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "1"}, {"name": "expect", "value": "200"}], "start": 1603203506328, "stop": 1603203506328, "uuid": "3c81b35f-9d04-4480-bb3e-56e82d6078ec", "historyId": "285257faee6d228f040d748d5ea83255", "testCaseId": "57815f8614d8cf4cba2d25e2a41cdc68", "fullName": "test_zuoye2.TestCalculator#test_sub", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_zuoye2"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "LZP"}, {"name": "thread", "value": "21344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_zuoye2"}]}