{"name": "test_mul[int_case_fail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100 == 200\n +  where 100 = round(100, 2)", "trace": "self = <hogwarts_learn.Test_pytestcase1.test_zuoye2.TestCalculator object at 0x0000022925005BB0>\nget_calc = <Cal_method.funcal.Calculator object at 0x0000022924F71370>, a = 100, b = 1, expect = 200\n\n    @pytest.mark.run(order=3)\n    @pytest.mark.parametrize('a,b,expect', get_datas()['MUL']['parametrize'], ids=get_datas()['MUL']['ids'])\n    def test_mul(self,get_calc, a, b, expect):\n        result = get_calc.mul(a, b)\n>       assert round(result, 2) == expect\nE       assert 100 == 200\nE        +  where 100 = round(100, 2)\n\ntest_zuoye2.py:27: AssertionError"}, "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "1"}, {"name": "expect", "value": "200"}], "start": 1603203506362, "stop": 1603203506363, "uuid": "163634fc-0573-4870-a2c5-114dbccdd636", "historyId": "0e97e750dcccad9a944e3eae6947899b", "testCaseId": "b69df24a11ae4046bfbe3c64ee67b387", "fullName": "test_zuoye2.TestCalculator#test_mul", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_zuoye2"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "LZP"}, {"name": "thread", "value": "21344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_zuoye2"}]}