{"name": "test_add[int_case_fail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 101 == 200\n +  where 101 = round(101, 2)", "trace": "self = <hogwarts_learn.Test_pytestcase1.test_zuoye2.TestCalculator object at 0x0000022924EE92E0>\nget_calc = <Cal_method.funcal.Calculator object at 0x0000022924F71370>, a = 100, b = 1, expect = 200\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.parametrize('a,b,expect', get_datas()['ADD']['parametrize'], ids=get_datas()['ADD']['ids'])\n    def test_add(self, get_calc,a, b, expect):\n        result = get_calc.add(a, b)\n>       assert round(result, 2) == expect\nE       assert 101 == 200\nE        +  where 101 = round(101, 2)\n\ntest_zuoye2.py:15: AssertionError"}, "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "1"}, {"name": "expect", "value": "200"}], "start": 1603203506202, "stop": 1603203506203, "uuid": "b6a7b00e-9287-4744-9a39-010d32db8309", "historyId": "2e9b771e881ed18a3679b24e80d83a86", "testCaseId": "0b2fcaae7149ba4c9935c28133ab26ab", "fullName": "test_zuoye2.TestCalculator#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_zuoye2"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "LZP"}, {"name": "thread", "value": "21344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_zuoye2"}]}